"""v0.2.1  fix associations 

Revision ID: 10329ed05a1a
Revises: 34c761d02790
Create Date: 2025-02-24 20:28:20.823875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10329ed05a1a'
down_revision: Union[str, None] = '34c761d02790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
