"""update user and cars model

Revision ID: 10606cbc79ea
Revises: 2b10f3372167
Create Date: 2025-01-20 13:21:14.487087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10606cbc79ea'
down_revision: Union[str, None] = '2b10f3372167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activ_cars', sa.Column('ltype', sa.String(), nullable=False))
    op.add_column('activ_cars', sa.Column('gear_type', sa.String(), nullable=True))
    op.alter_column('activ_cars', 'start_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('activ_cars', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('activ_cars', 'buy_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('property_cars', sa.Column('ltype', sa.String(), nullable=False))
    op.add_column('property_cars', sa.Column('gear_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verefy_email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('verefy_passport', sa.String(), nullable=False))
    op.add_column('users', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('users', 'verefyed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verefyed', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'image')
    op.drop_column('users', 'verefy_passport')
    op.drop_column('users', 'verefy_email')
    op.drop_column('property_cars', 'gear_type')
    op.drop_column('property_cars', 'ltype')
    op.alter_column('activ_cars', 'buy_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('activ_cars', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('activ_cars', 'start_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('activ_cars', 'gear_type')
    op.drop_column('activ_cars', 'ltype')
    # ### end Alembic commands ###
