"""v0.2.2 add association 

Revision ID: 86f4c60c9d17
Revises: 10329ed05a1a
Create Date: 2025-02-25 20:22:06.886728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f4c60c9d17'
down_revision: Union[str, None] = '10329ed05a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
