"""v0.1 add chat and assotiotion with chat/user/messages

Revision ID: 980272d420d7
Revises: 
Create Date: 2025-02-24 20:17:36.548556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980272d420d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seance', sa.DateTime(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('like_car_lots', sa.String(), nullable=False),
    sa.Column('like_property_cars', sa.String(), nullable=False),
    sa.Column('last_lot_time', sa.DateTime(), nullable=False),
    sa.Column('verefy_email', sa.String(), nullable=False),
    sa.Column('verefy_passport', sa.String(), nullable=False),
    sa.Column('ballance', sa.Double(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('passport_number')
    )
    op.create_table('activ_cars',
    sa.Column('ltype', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('engine_volume', sa.Double(), nullable=True),
    sa.Column('power', sa.Double(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('gear_type', sa.String(), nullable=True),
    sa.Column('range', sa.Double(), nullable=True),
    sa.Column('current_owner', sa.Integer(), nullable=True),
    sa.Column('start_price', sa.Double(), nullable=False),
    sa.Column('current_price', sa.Double(), nullable=False),
    sa.Column('buy_price', sa.Double(), nullable=False),
    sa.Column('price_step', sa.Double(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['current_owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_user_association',
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sending_date', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltype', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('engine_volume', sa.Double(), nullable=True),
    sa.Column('power', sa.Double(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('gear_type', sa.String(), nullable=True),
    sa.Column('range', sa.Double(), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('buy_date', sa.DateTime(), nullable=True),
    sa.Column('registration', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_association',
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_association')
    op.drop_table('property_cars')
    op.drop_table('message')
    op.drop_table('chat_user_association')
    op.drop_table('activ_cars')
    op.drop_table('users')
    op.drop_table('chat')
    # ### end Alembic commands ###
