"""update user, activ_cars model, delete gosnambers

Revision ID: de61e079ed56
Revises: 5c4c31e9a67e
Create Date: 2025-01-27 20:03:26.175897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de61e079ed56'
down_revision: Union[str, None] = '5c4c31e9a67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activ_cars', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('activ_cars', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('property_cars', 'buy_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('users', sa.Column('like_car_lots', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('like_property_cars', sa.String(), nullable=False, server_default=''))
    op.drop_column('users', 'property_gosnumbers')
    op.drop_column('users', 'have_gosnumber_lots')
    op.drop_column('users', 'property_cars')
    op.drop_column('users', 'have_car_lots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('have_car_lots', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('property_cars', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('have_gosnumber_lots', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('property_gosnumbers', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'like_property_cars')
    op.drop_column('users', 'like_car_lots')
    op.alter_column('property_cars', 'buy_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('activ_cars', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('activ_cars', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
